version: '3.8'

services:
  web:
    build: .
    ports: ["8000:8000"]
    volumes: [".:/app"]
    env_file: [.env]
    depends_on: 
      - db
      - redis
    networks:
      - app-network

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Bizhan2008
      POSTGRES_DB: clothing_db
    networks:
      - app-network

  redis:
    image: redis:7-alpine
    ports: ["6379:6379"]
    networks:
      - app-network

  celery_worker:
    build: .
    command: celery -A app.tasks worker --loglevel=info
    volumes: [".:/app"]
    env_file: [.env]
    depends_on:
      - redis
    networks:
      - app-network

# ←—— define the network here
networks:
  app-network:
    driver: bridge

# ←—— define your named volume too
volumes:
  postgres_data:
