"""initial migration

Revision ID: 729407189723
Revises: 
Create Date: 2025-06-12 06:41:47.866138

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '729407189723'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=True),
    sa.Column('is_premium', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('clothing_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('brand', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('gender', sa.String(), nullable=False),
    sa.Column('color', sa.String(), nullable=True),
    sa.Column('size', sa.String(), nullable=True),
    sa.Column('material', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('image_url', sa.String(), nullable=False),
    sa.Column('store_name', sa.String(), nullable=False),
    sa.Column('store_url', sa.String(), nullable=True),
    sa.Column('product_url', sa.String(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('occasions', sa.JSON(), nullable=True),
    sa.Column('weather_suitability', sa.JSON(), nullable=True),
    sa.Column('ai_generated_embedding', sa.JSON(), nullable=True),
    sa.Column('available', sa.Boolean(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clothing_items_id'), 'clothing_items', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_clothing_items_id'), table_name='clothing_items')
    op.drop_table('clothing_items')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
