"""Make gender nullable

Revision ID: db44f74ed18f
Revises: 729407189723
Create Date: 2025-06-18 03:52:08.095171

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db44f74ed18f'
down_revision: Union[str, None] = '729407189723'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('clothing_items', 'category',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('clothing_items', 'image_url',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('clothing_items', 'product_url',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('clothing_items', 'price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.drop_column('clothing_items', 'gender')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clothing_items', sa.Column('gender', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.alter_column('clothing_items', 'price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('clothing_items', 'product_url',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('clothing_items', 'image_url',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('clothing_items', 'category',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
