name: Deploy to Azure VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Deploy to Azure VM
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: 20.215.233.21
          username: bizhan
          key: ${{ secrets.AZURE_SSH_KEY }}
          script: |
            cd ~/AuarAI-back-nfac
            git pull origin main
            docker compose down
            docker compose up -d --build
